# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/python:3.6
    resource_class: small
    working_directory: ~/repo

commands:

  setup:
    steps:
      - run:
          name: Setup custom environment variables
          command: |
            echo "export GNS3_VERSION=\"${CIRCLE_TAG:-"v2.2.27"}\"" >> $BASH_ENV
            echo "export GNS3_NUMBER=\`echo \$GNS3_VERSION | sed \"s/^v//\"\`" >> $BASH_ENV

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install packet-python

      - run:
          name: Get builder device
          no_output_timeout: 15m
          command: |
            source env/bin/activate
            DEVICE_IP=`python3 .circleci/device.py ${EQUINIX_TOKEN} get "${EQUINIX_PROJECT}" ${DEVICE_TYPE}`
            echo "export DEVICE_IP=\"$DEVICE_IP\"" >> $BASH_ENV
            echo "Obtained device on $DEVICE_IP"
            ssh-keyscan -H ${DEVICE_IP} >> ~/.ssh/known_hosts

      - run:
          name: Clone repository on device
          command: |
            ssh root@${DEVICE_IP} "
              set -e
              if [ ! -d "~/gns3-vm" ]
              then
                git clone https://github.com/GNS3/gns3-vm.git
                cd gns3-vm
                git checkout focal-stable
              fi
            "

  finalize:
    steps:
      - run:
          name: Gather artifacts from device
          when: always
          command: |
            mkdir artifacts
            scp root@${DEVICE_IP}:"gns3-vm/GNS3*.zip" artifacts

      - run:
          name: Destroy device
          when: always
          command: |
            source env/bin/activate
            python3 .circleci/device.py ${EQUINIX_TOKEN} destroy "${EQUINIX_PROJECT}" ${DEVICE_TYPE}

      - run:
          name: Generate SHA256 checksums
          when: always
          command: |
            cd artifacts
            for file in *.zip
            do
              sha256sum "$file" > "$file.sha256"
              cat "$file.sha256"
              sha256sum -c "$file.sha256"
            done
            ls -l
            cd -

      - run:
          name: Deploying on Github and SourceForge
          when: always
          command: |
            source env/bin/activate

            python3 -m pip install -U pip

            git clone git@github.com:GNS3/gns3-build.git
            cd gns3-build
            pip3 install -r requirements.txt
            cd ..

            echo "Deploying version ${CIRCLE_TAG} on GitHub"
            for file in artifacts/GNS3.VM.*.{zip,sha256}
            do
              python3 gns3-build/upload.py ${CIRCLE_TAG} $file
            done

            echo "Deploying version ${CIRCLE_TAG} on SourceForge"
            ssh-keyscan -H frs.sourceforge.net >> ~/.ssh/known_hosts
            scp artifacts/GNS3.VM.* gns3build@frs.sourceforge.net:"/home/frs/project/gns-3/Releases/${CIRCLE_TAG}/"

      - store_artifacts:
          path: artifacts
          destination: artifacts

jobs:
  x86-build:
    executor: docker-executor

    environment:
        DEVICE_TYPE: c3.small.x86

    steps:
      - checkout
      - setup

      - run:
          name: Install VirtualBox
          command: |
            ssh root@${DEVICE_IP} "
              set -e
              apt update
              apt -y install linux-headers-\$(uname -r) zip unzip git
              wget -q -O- http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc | apt-key add -
              wget -q -O- http://download.virtualbox.org/virtualbox/debian/oracle_vbox.asc | apt-key add -
              apt-add-repository \"deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian \$(lsb_release -cs) contrib\"
              apt update
              apt -y install virtualbox-6.1
            "

      - run:
          name: Install VMWare
          command: |
            echo "
              set -e

              if [ ! -f "/tmp/VMware-Workstation-15.5.2-15785246.x86_64.bundle" ]
              then
                wget https://softwareupdate.vmware.com/cds/vmw-desktop/ws/15.5.2/15785246/linux/core/VMware-Workstation-15.5.2-15785246.x86_64.bundle.tar -O /tmp/VMWare.bundle.tar
                tar xvvf /tmp/VMWare.bundle.tar -C /tmp/
              fi

              chmod a+x /tmp/VMware-Workstation-15.5.2-15785246.x86_64.bundle

              /tmp/VMware-Workstation-15.5.2-15785246.x86_64.bundle --eulas-agreed --required --console
              /usr/lib/vmware/bin/vmware-vmx --new-sn ${VMWARE_15_SERIAL}
              /etc/init.d/vmware restart
            " > script.sh
            scp script.sh root@${DEVICE_IP}:
            ssh root@${DEVICE_IP} "bash script.sh"

      - run:
          name: Install Packer for amd64
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              if [ ! -f "/tmp/packer.zip" ]
              then
                wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_amd64.zip -O /tmp/packer.zip
              fi

              unzip -o /tmp/packer.zip -d /usr/local/bin/
            "

      - run:
          name: Release VirtualBox VM
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              cd gns3-vm

              if [ ! -e \"GNS3.VM.VirtualBox.${GNS3_NUMBER}.zip\" ];
              then
                ./release_virtualbox.sh ${GNS3_VERSION}
              fi
            "

      - run:
          name: Release Hyper-V VM
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              cd gns3-vm

              if [ ! -e \"GNS3.VM.Hyper-V.${GNS3_NUMBER}.zip\" ];
              then
                ./release_hyperv.sh ${GNS3_VERSION}
              fi
            "

      - run:
          name: Release KVM VM
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              cd gns3-vm

              if [ ! -e \"GNS3.VM.KVM.${GNS3_NUMBER}.zip\" ];
              then
                apt install -y qemu-utils
                ./release_kvm.sh ${GNS3_VERSION}
              fi
            "

      - run:
          name: Release VMWare VM
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              cd gns3-vm

              if [ ! -e \"GNS3.VM.VMware.Workstation.${GNS3_NUMBER}.zip\" ];
              then
                ./release_vmware.sh ${GNS3_VERSION}
              fi
            "

      - run:
          name: Release VMWare ESXI VM
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              cd gns3-vm

              cp \"GNS3.VM.VMware.Workstation.${GNS3_NUMBER}.zip\" /tmp/GNS3VM.VMware.${GNS3_NUMBER}.zip

              if [ ! -e \"GNS3.VM.VMware.ESXI.${GNS3_NUMBER}.zip\" ];
              then
                ./release_vmware_esxi.sh ${GNS3_VERSION}
              fi
            "

      - finalize

  arm64-build:
    executor: docker-executor

    environment:
        DEVICE_TYPE: c3.large.arm

    steps:
      - checkout
      - setup

      - run:
          name: Install Packer for ARM64
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              if [ ! -f "/tmp/packer.zip" ]
              then
                wget https://releases.hashicorp.com/packer/1.0.4/packer_1.0.4_linux_arm64.zip -O /tmp/packer.zip
              fi

              unzip -o /tmp/packer.zip -d /usr/local/bin/
            "

      - run:
          name: Release QEMU ARM64 VM
          command: |
            ssh root@${DEVICE_IP} "
              set -e

              cd gns3-vm

              if [ ! -e \"GNS3.VM.ARM64.${GNS3_NUMBER}.zip\" ];
              then
                ./release_qemu_arm64.sh ${GNS3_VERSION}
              fi
            "

      - finalize

workflows:
  build_only_on_tag:
    jobs:
      - x86-build:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
      - arm64-build:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
