# This file describes the network interfaces available on your system
# For more information, see netplan(5).

# Uncomment the following lines if you want to manually configure your network

network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - 172.16.1.1/24
      gateway4: 172.16.1.254
      nameservers:
          addresses: [8.8.8.8, 8.8.4.4]
